---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.yml: |-
    # my global config
    global:
      scrape_interval:     1m
      evaluation_interval: 1m

    alerting:
      alertmanagers:
      - static_configs:
        - targets:

    scrape_configs:
      - job_name: 'nexus'
        scrape_interval: 60s
        scheme: 'http'
        metrics_path: '/metrics.infra/prometheus'
        params:
          'service': ['all']
          'tracing': ['0']
        static_configs:
        - targets: ['test-ingressproxy.test:1080']
