---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: nats
  labels:
    name: nats
---
apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    name: test
