---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: kustomize
resources:
  - 00-namespaces.yaml  # Don't add namespaces as it prefixes them too
  - 02-filebeat.yaml # 1 is the Ingress provider
  - 03-jaeger.yaml
  - 04-prometheus.yaml
  - 05-nats-operator.yaml
  - 06-sealedsecret-crd.yaml
  - nats-cluster.yaml

vars:
  - name: JAEGER_COLLECTOR_SERVICE_HOST
    objref:
      apiVersion: v1
      kind: Service
      name: jaeger-collector
    fieldref:
      fieldpath: metadata.name
